name: ChangeOnMove
version: '${version}'
main: net.puf.changeonmove.ChangeOnMove
api-version: '1.20'

commands:
  changeonmove:
    description: Toggle block placement under players
    usage: /changeonmove <block-type>